### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/web-admin-dashboard#8]
Hi, @Gianfranco97 / @hectorerb 

I can see some errors in the demo http://flyve.org/web-admin-dashboard/

```console
TypeError: this._itemsManager is null[Learn More] ui.js:20429
```

```console
Error during service worker registration: DOMException {  } main.8dbde1a7.js:87770:81
```

**Comment by Gianfranco97** [comment]
The problem arises because we do not have HTTPS protocol on our sites and unfortunately we can not have it while we maintain a custom domain. Reviewing this topic I realized that even the service worker of the project sites stopped working for the same reason.

  ![captura de pantalla 2017-11-07 a la s 9 26 25 a m](https://user-images.githubusercontent.com/19965590/32496176-b25624fa-c39e-11e7-83e9-f8b30ad4c28f.png)

  ![captura de pantalla 2017-11-07 a la s 9 23 45 a m](https://user-images.githubusercontent.com/19965590/32496173-b1fbed8c-c39e-11e7-950a-53cd3353b2bb.png)

gh-pages of flyve-mdm-ios-inventory-agent:

 ![captura de pantalla 2017-11-07 a la s 9 22 24 a m](https://user-images.githubusercontent.com/19965590/32496175-b22c940a-c39e-11e7-88cb-775fc9736542.png)


**For more information:** 
- https://www.chromium.org/blink/serviceworker/service-worker-faq
- https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by ajsb85** [comment]
Ok, I will request HTTPS for flyve.org to the Teclib Hosting Team

And whats about this error?

```console
Error during service worker registration: DOMException {  } main.8dbde1a7.js:87770:81
```

**Comment by Gianfranco97** [comment]
It is caused precisely by what I said earlier.

  ![captura de pantalla 2017-11-07 a la s 9 40 13 a m](https://user-images.githubusercontent.com/19965590/32496589-204ac834-c3a0-11e7-9647-a1806ff27950.png)

**Comment by ajsb85** [comment]
Oh, this one

```console
TypeError: this._itemsManager is null[Learn More] ui.js:20429
```

**Comment by Gianfranco97** [comment]
Currently, the application is returning the following error when opening the detail of a user on a small screen (we are working on it).

``` console
Uncaught TypeError: Cannot read property 'dataSource' of null
```  
![captura de pantalla 2017-11-07 a la s 9 45 31 a m](https://user-images.githubusercontent.com/19965590/32497017-9206ffa0-c3a1-11e7-9776-3de685256cca.png)

 But I'm still not able to replicate the scenario for this error to appear:

```console
TypeError: this._itemsManager is null[Learn More] ui.js:20429
```

Could you please indicate at what moment it happens to you.

**Comment by ajsb85** [comment]
When I open an user

```console
TypeError: this._itemsManager is null[Learn More] ui.js:20429
	get ui.js:20429
	_fireInvokeEvent ui.js:9908
	fireInvokeEvent ui.js:9669
	onPointerUp ui.js:8443:17
	onPointerUp ui.js:10025
	handler ui.js:21488

```
![image](https://user-images.githubusercontent.com/663460/32497257-4390a12a-c3cc-11e7-942b-3b79806b6e83.png)

**Comment by Gianfranco97** [comment]
I can see that your error has the same nature as mine, only that this is different according to the browser, in chrome appears the one I just exposed and firefox appears yours. We are currently working to solve this problem. As soon as it is solved we will notify you.
